fileVersion: 1
id: "23"
mappingDefinitions:
  SAMPLE:
    database: COALESCE_SAMPLE_DATABASE
    schema: TPCH_SF001
  WORK:
    database: EVAN_EDW
    schema: STG
name: New Environment
type: Environment
